### ISSUE TITLE
How to change youtube_vos to COCO?

### ISSUE THREAD

**Issue by EasonEdison** [YingjieYin/Directional-Deep-Embedding-and-Appearance-Learning-for-Fast-Video-Object-Segmentation#1]
Hello, I'm having some difficulties now, could you tell me how to change youtube_vos to COCO?

**Comment by YingjieYin** [comment]
In our paper, in order to generate the Synthesis Videoes for training, we randomly select 1 to 5 segmented objects from COCO and a video from ILSVRC2017_VID, and then paste the selected objects after an affine transformation onto each frame of the selected video.    You don't need to  change youtube_vos to COCO.

**Comment by EasonEdison** [comment]
ok thank you for your reply!
